openapi: 3.0.0
info:
  title: Payment API Documentation
  version: 1.0.0
  description: API documentation for payment-related endpoints

components:
  schemas:
    PaymentIntent:
      type: object
      properties:
        amount:
          type: number
          description: Payment amount
        currency:
          type: string
          description: Payment currency code
        method:
          type: string
          enum: [credit_card, bank_transfer, crypto]
        details:
          type: object
          description: Additional payment details

    PaymentResponse:
      type: object
      properties:
        id:
          type: string
          description: Payment ID
        status:
          type: string
          enum: [pending, completed, failed]
        amount:
          type: number
        currency:
          type: string
        paymentMethod:
          type: string

    RefundRequest:
      type: object
      properties:
        amount:
          type: number
          description: Refund amount
        reason:
          type: string
          description: Reason for refund

paths:
  /api/payments/create:
    post:
      tags:
        - Payments
      summary: Create a new payment
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PaymentIntent'
      responses:
        '201':
          description: Payment created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentResponse'
        '400':
          description: Invalid request
        '401':
          description: Unauthorized
        '500':
          description: Server error

  /api/payments/{id}/confirm:
    post:
      tags:
        - Payments
      summary: Confirm a payment
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Payment confirmed successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentResponse'
        '400':
          description: Invalid request
        '404':
          description: Payment not found
        '500':
          description: Server error

  /api/payments/{id}/refund:
    post:
      tags:
        - Payments
      summary: Refund a payment
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RefundRequest'
      responses:
        '200':
          description: Refund processed successfully
        '400':
          description: Invalid request
        '404':
          description: Payment not found
        '500':
          description: Server error

  /api/payments/webhook/{provider}:
    post:
      tags:
        - Payments
      summary: Handle payment provider webhook
      parameters:
        - in: path
          name: provider
          required: true
          schema:
            type: string
            enum: [stripe, paypal, crypto]
      responses:
        '200':
          description: Webhook handled successfully
        '400':
          description: Invalid webhook payload
        '500':
          description: Server error